[package]
name="bike_parking_finder"
version="0.1.0"
authors=["juniorGreg <junior.gregoire@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
mime = "*"
iron = "*"
handlebars-iron = "*"
router = "*"
rand = "*"
staticfile = "*"
mount = "*"
chill = "*"
gettext-rs = "*"
time="*"
params="*"
