[package]
name="bike_parking_finder"
version="0.1.0"
authors=["juniorGreg <junior.gregoire@gmail.com>"]

[dependencies]
elastic_reqwest = "*"
elastic_types="*"
elastic_types_derive = "*"
reqwest = "*"
json_str = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
mime = "*"
iron = "*"
handlebars-iron = "*"
router = "*"
rand = "*"
staticfile = "*"
mount = "*"
gettext-rs = "*"
time="*"
params="*"
